export const recipes = [
  {
    id: 1,
    name: "Cake",
    cuisine: "American",
    ingredients: [
      "Chocolate powder",
      "Cocoa Powder",
      "Milk Powder",
      "Curd",
      "Fresh Cream",
      "All purpose Flour",
      "Granulated sugar",
      "Baking Powder",
      "Baking Soda",
      "Vanilla Essence",
    ],
    instructions: [
      " Preheat your oven to 350°F (175°C). Grease and flour a 9-inch round cake pan or line it with parchment paper.",
      "In a large mixing bowl, cream together the softened butter and sugar until light and fluffy.",
      "Add the eggs, one at a time, beating well after each addition. Stir in the vanilla extract.",
      "In a separate bowl, whisk together the flour, baking powder, and salt.",
      "Gradually add the dry ingredients to the butter mixture, alternating with the milk. Begin and end with the dry ingredients, mixing well after each addition. This helps to ensure a smooth batter.",
      "Once all the ingredients are combined, pour the batter into the prepared cake pan, spreading it evenly.",
      "Bake in the preheated oven for about 25-30 minutes, or until a toothpick inserted into the center of the cake comes out clean. The exact baking time may vary, so keep an eye on it.",
      "Remove the cake from the oven and let it cool in the pan for about 10 minutes.",
      "Then, transfer it to a wire rack to cool completely.",
      " Once the cake has cooled, you can frost it with your favorite frosting, such as buttercream or cream cheese frosting. Decorate as desired.",
      "Slice and serve the delicious homemade cake!",
    ],
  },
  {
    id: 2,
    name: "Pasta",
    cuisine: "Italian",
    ingredients: [
      "Chocolate powder",
      "Cocoa Powder",
      "Milk Powder",
      "Curd",
      "Fresh Cream",
      "All purpose Flour",
      "Granulated sugar",
      "Baking Powder",
      "Baking Soda",
      "Vanilla Essence",
    ],
    instructions: [
      " Preheat your oven to 350°F (175°C). Grease and flour a 9-inch round cake pan or line it with parchment paper.",
      "In a large mixing bowl, cream together the softened butter and sugar until light and fluffy.",
      "Add the eggs, one at a time, beating well after each addition. Stir in the vanilla extract.",
      "In a separate bowl, whisk together the flour, baking powder, and salt.",
      "Gradually add the dry ingredients to the butter mixture, alternating with the milk. Begin and end with the dry ingredients, mixing well after each addition. This helps to ensure a smooth batter.",
      "Once all the ingredients are combined, pour the batter into the prepared cake pan, spreading it evenly.",
      "Bake in the preheated oven for about 25-30 minutes, or until a toothpick inserted into the center of the cake comes out clean. The exact baking time may vary, so keep an eye on it.",
      "Remove the cake from the oven and let it cool in the pan for about 10 minutes.",
      "Then, transfer it to a wire rack to cool completely.",
      " Once the cake has cooled, you can frost it with your favorite frosting, such as buttercream or cream cheese frosting. Decorate as desired.",
      "Slice and serve the delicious homemade cake!",
    ],
  },
  {
    id: 3,
    name: "Enchiladas",
    cuisine: "Mexican",
    ingredients: [
      "Chocolate powder",
      "Cocoa Powder",
      "Milk Powder",
      "Curd",
      "Fresh Cream",
      "All purpose Flour",
      "Granulated sugar",
      "Baking Powder",
      "Baking Soda",
      "Vanilla Essence",
    ],
    instructions: [
      " Preheat your oven to 350°F (175°C). Grease and flour a 9-inch round cake pan or line it with parchment paper.",
      "In a large mixing bowl, cream together the softened butter and sugar until light and fluffy.",
      "Add the eggs, one at a time, beating well after each addition. Stir in the vanilla extract.",
      "In a separate bowl, whisk together the flour, baking powder, and salt.",
      "Gradually add the dry ingredients to the butter mixture, alternating with the milk. Begin and end with the dry ingredients, mixing well after each addition. This helps to ensure a smooth batter.",
      "Once all the ingredients are combined, pour the batter into the prepared cake pan, spreading it evenly.",
      "Bake in the preheated oven for about 25-30 minutes, or until a toothpick inserted into the center of the cake comes out clean. The exact baking time may vary, so keep an eye on it.",
      "Remove the cake from the oven and let it cool in the pan for about 10 minutes.",
      "Then, transfer it to a wire rack to cool completely.",
      " Once the cake has cooled, you can frost it with your favorite frosting, such as buttercream or cream cheese frosting. Decorate as desired.",
      "Slice and serve the delicious homemade cake!",
    ],
  },
  {
    id: 4,
    name: "Veg Kohlapuri",
    cuisine: "North Indian",
    ingredients: [
      "Chocolate powder",
      "Cocoa Powder",
      "Milk Powder",
      "Curd",
      "Fresh Cream",
      "All purpose Flour",
      "Granulated sugar",
      "Baking Powder",
      "Baking Soda",
      "Vanilla Essence",
    ],
    instructions: [
      " Preheat your oven to 350°F (175°C). Grease and flour a 9-inch round cake pan or line it with parchment paper.",
      "In a large mixing bowl, cream together the softened butter and sugar until light and fluffy.",
      "Add the eggs, one at a time, beating well after each addition. Stir in the vanilla extract.",
      "In a separate bowl, whisk together the flour, baking powder, and salt.",
      "Gradually add the dry ingredients to the butter mixture, alternating with the milk. Begin and end with the dry ingredients, mixing well after each addition. This helps to ensure a smooth batter.",
      "Once all the ingredients are combined, pour the batter into the prepared cake pan, spreading it evenly.",
      "Bake in the preheated oven for about 25-30 minutes, or until a toothpick inserted into the center of the cake comes out clean. The exact baking time may vary, so keep an eye on it.",
      "Remove the cake from the oven and let it cool in the pan for about 10 minutes.",
      "Then, transfer it to a wire rack to cool completely.",
      " Once the cake has cooled, you can frost it with your favorite frosting, such as buttercream or cream cheese frosting. Decorate as desired.",
      "Slice and serve the delicious homemade cake!",
    ],
  },
];
